### ISSUE TITLE
Gold Deposit doesn't have a name

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#141] opened 2016-10-28 19:25 UTC
In campaign mode I found a gold deposit but its' name was empty (see first screenshot) till I started to build a mine, then it had a normal name (see the second one).
![2016-10-28 20-58-18](https://cloud.githubusercontent.com/assets/1813101/19819451/c221045a-9d65-11e6-905f-12287c2962dd.png)
![2016-10-28 21-05-21](https://cloud.githubusercontent.com/assets/1813101/19819452/c2223f5a-9d65-11e6-88a3-3f98625df748.png)

**Comment by Andrettin** [comment] 2016-10-28 19:50
Thanks for reporting it! Unfortunately I couldn't reproduce it so far. At first I thought it was probably linked to it being a magic deposit with both a prefix and a suffix, but I found one which had both of those and still showed its name fine.

Did you happen to click on it while it was unbuilt? If so, did it have a name in the interface at least, even if not in the popup?

**Comment by KroArtem** [comment] 2016-10-28 19:55
Unfortunately I'm not sure whether I pressed on it or not.

**Comment by KroArtem** [comment] 2016-10-29 17:59
This time I started the campaign, played a bit, saved the game, exited, started Wyrmsun again, loaded the game and my mine deposit again doesn't have a name.
![2016-10-29 20-57-22](https://cloud.githubusercontent.com/assets/1813101/19831759/f487227c-9e22-11e6-92e5-2cbb1fbf423b.png)
![2016-10-29 20-57-33](https://cloud.githubusercontent.com/assets/1813101/19831760/f487fe68-9e22-11e6-8601-8bacdd2e2f81.png)

**Comment by Andrettin** [comment] 2016-10-30 08:24
Thanks! It was an issue which happened when loading a game. It's fixed now:
https://github.com/Andrettin/Wyrmgus/commit/f80ccff4c9f60f5e374e5ba4f3669cf6fd49601c

**Closed by Andrettin** 2016-10-30 08:24 UTC
