### ISSUE TITLE
[5.3.3] Dungeon door glitches

### ISSUE THREAD

**Issue by SenhorFlibble** [Andrettin/Wyrmsun#201] opened 2022-01-24 10:11 UTC
I've been playing with Legacy Quests in v5.3.3 and noticed oddities with dungeon doors in the first Dwarven quest:
- after a door is destroyed, my units keep attacking it and the half-destroyed door sprite does not disappear; units can walk through it as if it were no longer there though
- if a door is attacked by more than one unit and is instantly destroyed, in addition to the above the intact door sprite remains in place -- again, fully passable for units

It appears that only the first door to be destroyed in the dungeon works correctly, i.e. it disappears after being destroyed. All subsequent doors suffer from this bug.

I have not tested this with other dungeon missions.

On a separate note, I seem to be no longer able to take screenshots by pressing PrtSc in the game.

**Comment by Andrettin** [comment] 2022-01-24 17:45
Thanks for the report!

Hmm... this issue was supposed to have been fixed with 5.3.2. I will try it out.

About the screenshots, I changed the hotkey to F11 back in 5.0.0. IIRC there was an issue with using PrintScreen, but I can't recall offhand what it was.

**Comment by bmorel** [comment] 2022-01-26 11:27
> IIRC there was an issue with using PrintScreen, but I can't recall offhand what it was.

Conflicts with the OSes, maybe?

**Comment by Andrettin** [comment] 2022-01-26 11:56
> Conflicts with the OSes, maybe?

Yes, I think that was it :)

**Comment by Andrettin** [comment] 2022-01-27 07:13
I've managed to reproduce the bug and fix it:
https://github.com/Andrettin/Wyrmgus/commit/804ceecb8702fe59229e4768e9b2eb6146acd996

**Comment by Andrettin** [comment] 2022-02-02 07:22
I have released version 5.3.4 now, including the fix for this issue.

**Comment by SenhorFlibble** [comment] 2022-02-05 18:47
Thanks!

**Comment by Andrettin** [comment] 2022-02-07 18:54
Since this was fixed, I'm closing the issue :)

**Closed by Andrettin** 2022-02-07 18:54 UTC
