### ISSUE TITLE
Game freezes when you built Palisade.

### ISSUE THREAD

**Issue by HauptmannTod** [Andrettin/Wyrmsun#189] opened 2021-03-20 23:36 UTC
Hello, thank you for your work and I hope you continue it. I love this game. I missed something like that.
Can you tell me if I am missing something but when I build Palisade - my game freezes totally. Thank you.
Legacy quests on earth theaters - it throws me out to desktop in the second quest. On the first ques the ally does not do nothing at all, is this normal?

**Comment by Andrettin** [comment] 2021-03-21 07:37
Thank you for the bug reports! Someone else has mentioned to be an issue when building walls as well, but I have been unable to reproduce it so far.

I will take a look on the second quest crash.

About the first quest, it is normal that the ally does nothing, yes.

**Comment by HauptmannTod** [comment] 2021-03-21 12:41
Thank you for the quick response - just build palisade - when it is finished - the game just freezes like screenshot. Also if that helps - the game is with all add-ons, and with administrator privileges on the executable. If I can help in any other way just say :)

**Comment by Andrettin** [comment] 2021-09-19 16:42
This bug has been fixed with version 5.0.0 :)

**Closed by Andrettin** 2021-09-19 16:42 UTC
