### ISSUE TITLE
Expert miners with skilled miners don't have an option to build

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#148] opened 2016-12-22 21:29 UTC
See screenshot. In case I choose only Expert or only Skilled miners, I can build, otherwise no.
![2016-12-23 00-30-09](https://cloud.githubusercontent.com/assets/1813101/21441107/e75f9a72-c8af-11e6-8354-800198190f7a.png)

**Comment by Andrettin** [comment] 2016-12-24 12:43
Thanks for the report, the issue is fixed now :)

https://github.com/Andrettin/Wyrmgus/commit/224e7ab4d3c6f08127bdb42d26ad16f3cb587759
https://github.com/Andrettin/Wyrmsun/commit/7bbc1ed540cd93612426b004ea9e75dc53c22d20

**Closed by Andrettin** 2016-12-24 12:43 UTC
