### ISSUE TITLE
Game freezes at different points of the game

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#47] opened 2015-12-30 01:19 UTC
Wyrmsun & Wyrmgus the latest.
When I try to load a new game, it freezes, Sometimes on the main menu, sometimes after loading a new game, sometimes when I want to choose quest. There is no valuable output in terminal. This problem was also mentioned here: http://forum.freegamedev.net/viewtopic.php?f=22&t=6607&start=25#p67082

Removing all old data files (autosaves and saves) didn't help.

**Comment by a-detiste** [comment] 2015-12-30 05:20
Got this one too with the Steam runtime, bu not with ./run.sh

**Comment by Andrettin** [comment] 2015-12-31 15:08
Thank you for the report! It seems to be a Linux-only issue, which is why it didn't appear for me during testing.

A similar report reads thus:

"The game tightly hangs randomly in a few seconds after start, without depending on other actions with it.
Firstly, the sound disappears (maybe the problem with ALSA?), but the ingame cursor is still moving. After clicking on any button the game hangs finally. Only 'kill -KILL <pid>' helps.

In addition if in fullscreen mode, the X session stays uncleared globally after game crash.

Debian Linux x86_64, GeForce GT 730, nvidia driver ver 352.55 (from SteamOS repo).
All other steam games work fine."

If it is indeed a sound-related issue, then it could be due to this commit:
https://github.com/Andrettin/Wyrmgus/commit/3c04f605c01d6b8d3d4391ea7a1bd4c457579acd

**Comment by Andrettin** [comment] 2015-12-31 19:05
I reverted that commit here:
https://github.com/Andrettin/Wyrmgus/commit/51f38ed91beb28878a404f7b076ae8d35de4ae79

Could you let me know if the game works fine with the new commit?

**Comment by Andrettin** [comment] 2015-12-31 19:27
I unfortunately could not reproduce the issue with my Ubuntu 12.02 virtual machine.

**Comment by KroArtem** [comment] 2015-12-31 22:12
Yup, it works with reverted changes.

**Comment by Andrettin** [comment] 2016-01-01 15:38
Thanks for letting me know :)

marcelofg55 sent me a fix to the issue, which I've now implemented:
https://github.com/Andrettin/Wyrmgus/commit/408eba40e453a558f84d614d10e51828c8325c83

**Comment by Andrettin** [comment] 2016-01-02 21:11
Confirmed fixed with marcelofg's patch.

**Closed by Andrettin** 2016-01-02 21:11 UTC
